CREATE TABLE `vendedor` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`nome` VARCHAR(120) NOT NULL DEFAULT '0',
	`endereco` VARCHAR(200) NOT NULL DEFAULT '0',
	`email` VARCHAR(100) NOT NULL DEFAULT '0',
	`telefone` VARCHAR(80) NOT NULL DEFAULT '0',
	`login` VARCHAR(80) NOT NULL DEFAULT '0',
	`senha` VARCHAR(80) NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

